# Generated by Django 4.2 on 2023-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapSmart', '0003_rename_listing_message_ad_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
