# Generated by Django 4.2 on 2023-05-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwapSmart', '0004_ad_condition_ad_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
